import {test,expect} from '@playwright/test';

test('every generated NACA preset sends finite-base geometry to all four solver modes',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.requests=[];window.Worker=class {postMessage(data){window.requests.push(structuredClone(data));}terminate(){}};});
 for(const preset of ['single','flap','three'])for(const mode of ['inviscid','coupled','streamtube-grid','streamtube-bl']){
  await page.goto('/');await page.selectOption('#preset',preset);await page.selectOption('#flow-model',mode);
  await page.click('#solve-button');
  await expect.poll(()=>page.evaluate(()=>window.requests.filter(r=>r.caseData).length)).toBeGreaterThan(0);
  const input=await page.evaluate(()=>window.requests.filter(r=>r.caseData).at(-1).caseData);
  for(const element of input.elements){
   expect(element.trailingEdge.kind).toBe('finite-base');
   const upper=element.points[element.trailingEdge.upperIndex],lower=element.points[element.trailingEdge.lowerIndex];
   expect(Math.hypot(upper.x-lower.x,upper.y-lower.y)).toBeGreaterThan(0);
   expect(element.points.at(-1)).toEqual(element.points[0]);
  }
 }
 expect(errors).toEqual([]);
});

// Use the real worker and the finite-base geometry generated by the app.
for (const {mach,viscous=false} of [{mach:.01},{mach:.2},{mach:.01,viscous:true}])
test(`NACA 0012 64x24 ${viscous ? 'converges viscous' : 'converges inviscid'} at Mach ${mach}`,async({page})=>{
 test.setTimeout(600_000);
 await page.addInitScript(()=>{
  const NativeWorker=window.Worker;window.nacaRuns=[];
  window.Worker=class extends NativeWorker {
   postMessage(request,...rest){
    const run={input:request.caseData,id:request.id,stages:[]};window.nacaRuns.push(run);
    this.addEventListener('message',({data})=>{
     if(data.id!==run.id)return;
     if(data.type==='error')run.error=data.message;
     if(data.type==='flow-stage')run.stages.push(data);
     if(data.type==='iteration'&&data.iteration?.stage==='euler')run.euler=data.iteration;
     if(data.type==='result'){
      const r=data.result;
      run.result={status:r.status,mach:r.mach,alpha:r.alpha,residual:r.diagnostics?.equationResidual,
       iterations:r.diagnostics?.iterations,reason:r.diagnostics?.reason,gridValid:r.mesh?.quality?.valid};
     }
    });
    return super.postMessage(request,...rest);
   }
  };
 });
 await page.goto('/');await page.locator('#stop-button').click();
 await page.selectOption('#preset','single');await page.selectOption('#flow-model',viscous?'streamtube-bl':'streamtube-grid');
 if(viscous){
  await page.fill('#quad-reynolds','1000000');await page.fill('#quad-ncrit','9');
  await page.selectOption('#quad-transition','automatic');
 }
 await page.selectOption('#grid-intervals','64');await page.selectOption('#grid-tubes','24');
 await page.selectOption('#grid-inlet','32');await page.selectOption('#grid-outlet','32');
 await page.fill('#quad-mach',String(mach));await page.fill('#alpha-number','4');
 await expect(page.locator('#grid-surface-spacing')).toHaveValue('automatic');
 await expect(page.locator('#grid-elliptic')).toBeChecked();
 await expect(page.locator('#euler-startup')).toHaveValue('standard');
 await page.click('#solve-button');
 await page.waitForFunction(()=>{
  const r=window.nacaRuns.at(-1);return r?.input?.gridTubes===24&&(r.result||r.error);
 },null,{timeout:550_000});
 const run=await page.evaluate(()=>window.nacaRuns.at(-1));
 console.log(JSON.stringify(run.result??run.error));
 expect(run.input).toMatchObject({gridIntervals:64,gridTubes:24,gridInletIntervals:32,gridOutletIntervals:32,
  mach,alpha:4,quadBoundaryLayers:viscous});
 const element=run.input.elements[0];expect(element.trailingEdge.kind).toBe('finite-base');
 expect(element.points[0].y).toBeCloseTo(.00126,14);
 expect(element.points[element.trailingEdge.lowerIndex].y).toBeCloseTo(-.00126,14);
 expect(run.error).toBeUndefined();
 if(viscous){
  expect(run.stages.some(s=>s.stage==='boundary-layer-initialization'
   &&s.boundaryLayerInitialization?.accepted===true
   &&s.boundaryLayerInitialization.panelProfile?.accepted===true
   &&s.boundaryLayerInitialization.thicknessFactor===1)).toBe(true);
  expect(run.stages.some(s=>s.stage==='coupled')).toBe(true);
  expect(run.result).toMatchObject({status:'research-coupled-equations-converged',mach,alpha:4,gridValid:true});
  expect(run.result.residual).toBeLessThanOrEqual(1e-10);
  expect(run.result.iterations).toBeGreaterThan(0);
  expect(run.result.iterations).toBeLessThanOrEqual(40);
  return;
 }
 expect(run.result).toMatchObject({status:'research-converged',mach,alpha:4,gridValid:true});
 expect(run.result.residual).toBeLessThanOrEqual(1e-10);
 expect(run.result.iterations).toBeLessThanOrEqual(mach === .01 ? 12 : 20);
 await expect(page.locator('#status')).toHaveText('Euler converged · research');
});
